namespace MinecraftFirewall.Proxy.Protocol;

/// <summary>Packet IDs a specific protocol version needs for Play-state inspection. Configuration's
/// Finish Configuration (serverbound) is included too — it's the client's Play-state entry marker.</summary>
public sealed record PlayStatePacketIds(
    int ConfigurationFinishConfigurationServerbound,
    int PlayChatServerbound,
    int PlayChatCommandServerbound,
    int PlayChatCommandSignedServerbound,
    int PlayDisconnectClientbound,
    int PlayMovePlayerPosServerbound,
    int PlayMovePlayerPosRotServerbound,
    int PlayMovePlayerRotServerbound,
    int PlayMovePlayerStatusOnlyServerbound,
    int PlayCustomPayloadServerbound,
    int PlayInteractServerbound,
    int PlaySwingServerbound,
    int PlaySignUpdateServerbound,
    int PlayEditBookServerbound,
    int PlaySystemChatClientbound,
    int[] PlayActionServerbound)
{
    /// <summary>True for any of the four serverbound movement packets — the ones carrying coordinates
    /// a malformed or hostile client can use to upset a server, and the ones a movement cheat has to
    /// send in order to cheat.</summary>
    public bool IsMovement(int packetId) =>
        packetId == PlayMovePlayerPosServerbound ||
        packetId == PlayMovePlayerPosRotServerbound ||
        packetId == PlayMovePlayerRotServerbound ||
        packetId == PlayMovePlayerStatusOnlyServerbound;

    /// <summary>
    /// True for the packets that let a player act on the world: moving, hitting, placing, opening
    /// containers, using items.
    ///
    /// A blocklist rather than an allowlist, and deliberately so. Holding a player still while they
    /// authenticate means refusing what they *do*, not refusing everything — a connection that stops
    /// answering keep-alives is disconnected by the backend within thirty seconds, and the player would
    /// see a timeout rather than the password prompt they were sent. Everything not named here keeps
    /// flowing, so the session stays healthy while the player is frozen.
    /// </summary>
    public bool IsPlayerAction(int packetId) => Array.IndexOf(PlayActionServerbound, packetId) >= 0;

    /// <summary>Packets carrying free-form player text. These are what a payload scanner needs to see:
    /// every one of them ends up somewhere that interprets strings — a log line, a plugin, a sign, a
    /// book — which is exactly where a string-injection exploit lands.</summary>
    public bool IsTextCarrying(int packetId) =>
        packetId == PlayChatServerbound ||
        packetId == PlayChatCommandServerbound ||
        packetId == PlayChatCommandSignedServerbound ||
        packetId == PlaySignUpdateServerbound ||
        packetId == PlayEditBookServerbound;
}

/// <summary>
/// Maps a client's declared protocol version to the packet IDs Stage 3 needs to inspect. Every entry
/// here must be sourced from Mojang's own generated data report for that exact version
/// (`java -jar server.jar --reports` → generated/reports/packets.json — see docs/protocol/README.md),
/// never extrapolated from a nearby version. The generated tables below show exactly why: serverbound
/// chat is 0x06 on protocol 767, 0x07 on 768-770 and 0x08 from 771, and clientbound system chat moves
/// four times across the same range. An unrecognized version means "stop inspecting, keep proxying at
/// the frame level" — never a best-guess fallback.
/// </summary>
public static class ProtocolVersionRegistry
{
    /// <summary>
    /// Every protocol version whose packet IDs this project has actually verified, generated by
    /// running each version's own server jar with Mojang's data generator. Regenerate with
    /// tools/generate-protocol-tables.py when a new Minecraft release comes out.
    ///
    /// Currently: 1.21 (767), 1.21.2 (768), 1.21.4 (769), 1.21.5 (770), 1.21.6 (771), 1.21.7 (772), 1.21.10 (773), 1.21.11 (774).
    /// </summary>
    private static readonly Dictionary<int, PlayStatePacketIds> Versions = new()
    {
        // Protocol 767 = Minecraft 1.21. Sourced from
        // docs/protocol/packets-767.json, the unmodified report that version's own server
        // jar produced.
        [767] = new PlayStatePacketIds(
            ConfigurationFinishConfigurationServerbound: 0x03,
            PlayChatServerbound: 0x06,
            PlayChatCommandServerbound: 0x04,
            PlayChatCommandSignedServerbound: 0x05,
            PlayDisconnectClientbound: 0x1D,
            PlayMovePlayerPosServerbound: 0x1A,
            PlayMovePlayerPosRotServerbound: 0x1B,
            PlayMovePlayerRotServerbound: 0x1C,
            PlayMovePlayerStatusOnlyServerbound: 0x1D,
            PlayCustomPayloadServerbound: 0x12,
            PlayInteractServerbound: 0x16,
            PlaySwingServerbound: 0x36,
            PlaySignUpdateServerbound: 0x35,
            PlayEditBookServerbound: 0x14,
            PlaySystemChatClientbound: 0x6C,
            PlayActionServerbound: [0x0E, 0x16, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x24, 0x26, 0x2F, 0x32, 0x36, 0x38, 0x39]),
        // Protocol 768 = Minecraft 1.21.2. Sourced from
        // docs/protocol/packets-768.json, the unmodified report that version's own server
        // jar produced.
        [768] = new PlayStatePacketIds(
            ConfigurationFinishConfigurationServerbound: 0x03,
            PlayChatServerbound: 0x07,
            PlayChatCommandServerbound: 0x05,
            PlayChatCommandSignedServerbound: 0x06,
            PlayDisconnectClientbound: 0x1D,
            PlayMovePlayerPosServerbound: 0x1C,
            PlayMovePlayerPosRotServerbound: 0x1D,
            PlayMovePlayerRotServerbound: 0x1E,
            PlayMovePlayerStatusOnlyServerbound: 0x1F,
            PlayCustomPayloadServerbound: 0x14,
            PlayInteractServerbound: 0x18,
            PlaySwingServerbound: 0x38,
            PlaySignUpdateServerbound: 0x37,
            PlayEditBookServerbound: 0x16,
            PlaySystemChatClientbound: 0x73,
            PlayActionServerbound: [0x10, 0x18, 0x1C, 0x1D, 0x1E, 0x1F, 0x20, 0x26, 0x28, 0x31, 0x34, 0x38, 0x3A, 0x3B]),
        // Protocol 769 = Minecraft 1.21.4. Sourced from
        // docs/protocol/packets-769.json, the unmodified report that version's own server
        // jar produced.
        [769] = new PlayStatePacketIds(
            ConfigurationFinishConfigurationServerbound: 0x03,
            PlayChatServerbound: 0x07,
            PlayChatCommandServerbound: 0x05,
            PlayChatCommandSignedServerbound: 0x06,
            PlayDisconnectClientbound: 0x1D,
            PlayMovePlayerPosServerbound: 0x1C,
            PlayMovePlayerPosRotServerbound: 0x1D,
            PlayMovePlayerRotServerbound: 0x1E,
            PlayMovePlayerStatusOnlyServerbound: 0x1F,
            PlayCustomPayloadServerbound: 0x14,
            PlayInteractServerbound: 0x18,
            PlaySwingServerbound: 0x3A,
            PlaySignUpdateServerbound: 0x39,
            PlayEditBookServerbound: 0x16,
            PlaySystemChatClientbound: 0x73,
            PlayActionServerbound: [0x10, 0x18, 0x1C, 0x1D, 0x1E, 0x1F, 0x20, 0x27, 0x29, 0x33, 0x36, 0x3A, 0x3C, 0x3D]),
        // Protocol 770 = Minecraft 1.21.5. Sourced from
        // docs/protocol/packets-770.json, the unmodified report that version's own server
        // jar produced.
        [770] = new PlayStatePacketIds(
            ConfigurationFinishConfigurationServerbound: 0x03,
            PlayChatServerbound: 0x07,
            PlayChatCommandServerbound: 0x05,
            PlayChatCommandSignedServerbound: 0x06,
            PlayDisconnectClientbound: 0x1C,
            PlayMovePlayerPosServerbound: 0x1C,
            PlayMovePlayerPosRotServerbound: 0x1D,
            PlayMovePlayerRotServerbound: 0x1E,
            PlayMovePlayerStatusOnlyServerbound: 0x1F,
            PlayCustomPayloadServerbound: 0x14,
            PlayInteractServerbound: 0x18,
            PlaySwingServerbound: 0x3B,
            PlaySignUpdateServerbound: 0x3A,
            PlayEditBookServerbound: 0x16,
            PlaySystemChatClientbound: 0x72,
            PlayActionServerbound: [0x10, 0x18, 0x1C, 0x1D, 0x1E, 0x1F, 0x20, 0x27, 0x29, 0x33, 0x36, 0x3B, 0x3E, 0x3F]),
        // Protocol 771 = Minecraft 1.21.6. Sourced from
        // docs/protocol/packets-771.json, the unmodified report that version's own server
        // jar produced.
        [771] = new PlayStatePacketIds(
            ConfigurationFinishConfigurationServerbound: 0x03,
            PlayChatServerbound: 0x08,
            PlayChatCommandServerbound: 0x06,
            PlayChatCommandSignedServerbound: 0x07,
            PlayDisconnectClientbound: 0x1C,
            PlayMovePlayerPosServerbound: 0x1D,
            PlayMovePlayerPosRotServerbound: 0x1E,
            PlayMovePlayerRotServerbound: 0x1F,
            PlayMovePlayerStatusOnlyServerbound: 0x20,
            PlayCustomPayloadServerbound: 0x15,
            PlayInteractServerbound: 0x19,
            PlaySwingServerbound: 0x3C,
            PlaySignUpdateServerbound: 0x3B,
            PlayEditBookServerbound: 0x17,
            PlaySystemChatClientbound: 0x72,
            PlayActionServerbound: [0x11, 0x19, 0x1D, 0x1E, 0x1F, 0x20, 0x21, 0x28, 0x2A, 0x34, 0x37, 0x3C, 0x3F, 0x40]),
        // Protocol 772 = Minecraft 1.21.7. Sourced from
        // docs/protocol/packets-772.json, the unmodified report that version's own server
        // jar produced.
        [772] = new PlayStatePacketIds(
            ConfigurationFinishConfigurationServerbound: 0x03,
            PlayChatServerbound: 0x08,
            PlayChatCommandServerbound: 0x06,
            PlayChatCommandSignedServerbound: 0x07,
            PlayDisconnectClientbound: 0x1C,
            PlayMovePlayerPosServerbound: 0x1D,
            PlayMovePlayerPosRotServerbound: 0x1E,
            PlayMovePlayerRotServerbound: 0x1F,
            PlayMovePlayerStatusOnlyServerbound: 0x20,
            PlayCustomPayloadServerbound: 0x15,
            PlayInteractServerbound: 0x19,
            PlaySwingServerbound: 0x3C,
            PlaySignUpdateServerbound: 0x3B,
            PlayEditBookServerbound: 0x17,
            PlaySystemChatClientbound: 0x72,
            PlayActionServerbound: [0x11, 0x19, 0x1D, 0x1E, 0x1F, 0x20, 0x21, 0x28, 0x2A, 0x34, 0x37, 0x3C, 0x3F, 0x40]),
        // Protocol 773 = Minecraft 1.21.10. Sourced from
        // docs/protocol/packets-773.json, the unmodified report that version's own server
        // jar produced.
        [773] = new PlayStatePacketIds(
            ConfigurationFinishConfigurationServerbound: 0x03,
            PlayChatServerbound: 0x08,
            PlayChatCommandServerbound: 0x06,
            PlayChatCommandSignedServerbound: 0x07,
            PlayDisconnectClientbound: 0x20,
            PlayMovePlayerPosServerbound: 0x1D,
            PlayMovePlayerPosRotServerbound: 0x1E,
            PlayMovePlayerRotServerbound: 0x1F,
            PlayMovePlayerStatusOnlyServerbound: 0x20,
            PlayCustomPayloadServerbound: 0x15,
            PlayInteractServerbound: 0x19,
            PlaySwingServerbound: 0x3C,
            PlaySignUpdateServerbound: 0x3B,
            PlayEditBookServerbound: 0x17,
            PlaySystemChatClientbound: 0x77,
            PlayActionServerbound: [0x11, 0x19, 0x1D, 0x1E, 0x1F, 0x20, 0x21, 0x28, 0x2A, 0x34, 0x37, 0x3C, 0x3F, 0x40]),
        // Protocol 774 = Minecraft 1.21.11. Sourced from
        // docs/protocol/packets-774.json, the unmodified report that version's own server
        // jar produced.
        [774] = new PlayStatePacketIds(
            ConfigurationFinishConfigurationServerbound: 0x03,
            PlayChatServerbound: 0x08,
            PlayChatCommandServerbound: 0x06,
            PlayChatCommandSignedServerbound: 0x07,
            PlayDisconnectClientbound: 0x20,
            PlayMovePlayerPosServerbound: 0x1D,
            PlayMovePlayerPosRotServerbound: 0x1E,
            PlayMovePlayerRotServerbound: 0x1F,
            PlayMovePlayerStatusOnlyServerbound: 0x20,
            PlayCustomPayloadServerbound: 0x15,
            PlayInteractServerbound: 0x19,
            PlaySwingServerbound: 0x3C,
            PlaySignUpdateServerbound: 0x3B,
            PlayEditBookServerbound: 0x17,
            PlaySystemChatClientbound: 0x77,
            PlayActionServerbound: [0x11, 0x19, 0x1D, 0x1E, 0x1F, 0x20, 0x21, 0x28, 0x2A, 0x34, 0x37, 0x3C, 0x3F, 0x40]),
    };

    public static bool TryGet(int protocolVersion, out PlayStatePacketIds ids) =>
        Versions.TryGetValue(protocolVersion, out ids!);

    /// <summary>The protocol numbers this build can inspect, for a log line that tells an admin what
    /// to do rather than only what went wrong.</summary>
    public static string SupportedVersionsDescription => string.Join(", ", Versions.Keys.Order());

    public static IReadOnlyCollection<int> SupportedVersions => Versions.Keys;
}
