namespace MinecraftFirewall.App.Services;

/// <summary>
/// Every value each player-facing message has shipped with in an earlier release.
///
/// This exists to answer one question safely: has somebody edited this message, or is it simply old?
/// Configuration wins over the compiled defaults — which is right, it is their file — but it means a
/// default that improves in a new release never reaches anybody who installed an older one. Their
/// prompts stay as they were, and there is nothing to tell them why.
///
/// A message whose current value is one this project shipped is a message nobody has touched, and
/// bringing it up to date takes nothing from them. A message that matches none of them was written by
/// a person, and is never touched.
///
/// Generated by tools/generate-message-history.py, which reads every v1.* tag rather than trusting
/// anybody to maintain a list. A list kept by hand would rot the first time somebody forgot to add to
/// it, and it would fail in the worst direction: silently replacing something somebody wrote.
/// </summary>
public static class MessageDefaultHistory
{
    /// <summary>Message key to the values it has had in earlier releases, newest release last.</summary>
    public static readonly IReadOnlyDictionary<string, string[]> PreviousDefaults =
    new Dictionary<string, string[]>(StringComparer.Ordinal)
    {
        ["AlreadyRegistered"] =
        [
            "You already have a password here. To change it, type  changepassword <current> <new>  — you need the current one, even from this computer.",
        ],
        ["AuthenticationAccepted"] =
        [
            "Authenticated. Have fun.",
        ],
        ["AuthenticationTimedOut"] =
        [
            "You did not register or log in within the time allowed. Reconnect and try again.",
        ],
        ["CurrentPasswordWrong"] =
        [
            "That is not your current password, so nothing was changed.",
        ],
        ["DamagedWhileAuthenticating"] =
        [
            "Something attacked you while you were logging in, so you were disconnected before you could die. Rejoin and log in straight away.",
        ],
        ["LoginPrompt"] =
        [
            "Welcome back. Type  /login <password>  to continue. You cannot move or interact until you do.",
            "Welcome back. Type  login <password>  in chat to continue. You cannot move or interact until you do.",
        ],
        ["LoginSubtitle"] =
        [
            "Type in chat:  login <password>",
        ],
        ["LoginTitle"] =
        [
            "Login required",
        ],
        ["NoPasswordToChange"] =
        [
            "You do not have a password on this server yet. Type  register <password>  to set one.",
        ],
        ["PasswordChanged"] =
        [
            "Your password has been changed. The old one no longer works.",
        ],
        ["PasswordTooShort"] =
        [
            "That password is too short — it needs at least {0} characters. Try again with  /register <password>",
            "That password is too short — it needs at least {0} characters. Try again with  register <password>",
        ],
        ["PremiumLockArmed"] =
        [
            "Ready. Rejoin now with the real Minecraft account that owns this name, and it will be locked to it. If you rejoin with anything else, nothing is recorded and you simply play as usual.",
        ],
        ["PremiumLockExplain"] =
        [
            "Locking your name means only your real Minecraft account can ever use it on this server, from any address, and you will never be asked for a password. This cannot be undone by you afterwards. To go ahead, type /premium confirm — you will be disconnected, and must rejoin using the genuine account.",
        ],
        ["PremiumLockSucceeded"] =
        [
            "Your name is now locked to this Minecraft account. Nobody else can use it on this server.",
        ],
        ["PremiumOfferDuringRegistration"] =
        [
            "Own this name on a real Minecraft account? Type  premium  instead, and it will be locked to that account — no password to remember, and nobody else can ever use the name here.",
        ],
        ["RegistrationPrompt"] =
        [
            "This server requires an account. Type  /register <password>  to create one. You cannot move or interact until you do. Choose something you have not used elsewhere.",
            "This server requires an account. Type  register <password>  in chat to create one. You cannot move or interact until you do. Choose something you have not used elsewhere.",
        ],
        ["RegistrationSubtitle"] =
        [
            "Type in chat:  register <password>",
        ],
        ["RegistrationTitle"] =
        [
            "Registration required",
        ],
    };

    /// <summary>True when this text is one an earlier release shipped, which means nobody has edited
    /// it and replacing it takes nothing away.</summary>
    public static bool IsAnUneditedDefault(string key, string value) =>
        PreviousDefaults.TryGetValue(key, out string[]? values) &&
        Array.IndexOf(values, value) >= 0;
}
