import json
import sys
from pathlib import Path

WORK = Path(sys.argv[1]) / 'protocols'
tables = json.loads((WORK / 'tables.json').read_text(encoding='utf-8'))

entries = []
for protocol in sorted(tables, key=int):
    t = tables[protocol]
    actions = ', '.join(f'0x{a:02X}' for a in t['actions'])
    entries.append(f'''        // Protocol {t['protocol']} = Minecraft {t['version']}. Sourced from
        // docs/protocol/packets-{t['protocol']}.json, the unmodified report that version's own server
        // jar produced.
        [{t['protocol']}] = new PlayStatePacketIds(
            ConfigurationFinishConfigurationServerbound: 0x{t['config_finish']:02X},
            PlayChatServerbound: 0x{t['chat']:02X},
            PlayChatCommandServerbound: 0x{t['chat_command']:02X},
            PlayChatCommandSignedServerbound: 0x{t['chat_command_signed']:02X},
            PlayDisconnectClientbound: 0x{t['disconnect']:02X},
            PlayMovePlayerPosServerbound: 0x{t['move_pos']:02X},
            PlayMovePlayerPosRotServerbound: 0x{t['move_pos_rot']:02X},
            PlayMovePlayerRotServerbound: 0x{t['move_rot']:02X},
            PlayMovePlayerStatusOnlyServerbound: 0x{t['move_status']:02X},
            PlayCustomPayloadServerbound: 0x{t['custom_payload']:02X},
            PlayInteractServerbound: 0x{t['interact']:02X},
            PlaySwingServerbound: 0x{t['swing']:02X},
            PlaySignUpdateServerbound: 0x{t['sign_update']:02X},
            PlayEditBookServerbound: 0x{t['edit_book']:02X},
            PlaySystemChatClientbound: 0x{t['system_chat']:02X},
            PlayActionServerbound: [{actions}]),''')

p = Path('src/MinecraftFirewall.Proxy/Protocol/ProtocolVersionRegistry.cs')
s = p.read_text(encoding='utf-8')

start = s.index('    private static readonly Dictionary<int, PlayStatePacketIds> Versions = new()')
end = s.index('    };', start) + len('    };')

supported = ', '.join(f"{tables[k]['version']} ({k})" for k in sorted(tables, key=int))

block = f'''    /// <summary>
    /// Every protocol version whose packet IDs this project has actually verified, generated by
    /// running each version's own server jar with Mojang's data generator. Regenerate with
    /// tools/generate-protocol-tables.py when a new Minecraft release comes out.
    ///
    /// Currently: {supported}.
    /// </summary>
    private static readonly Dictionary<int, PlayStatePacketIds> Versions = new()
    {{
{chr(10).join(entries)}
    }};'''

s = s[:start] + block + s[end:]

# The old single-version comment on the class is no longer accurate.
s = s.replace('''/// never extrapolated from a nearby version: protocol 774 and 776 (two releases apart) already
/// disagreed on these exact IDs during this project's own verification. An unrecognized version means
/// "stop inspecting, keep proxying at the frame level" — never a best-guess fallback.''',
'''/// never extrapolated from a nearby version. The generated tables below show exactly why: serverbound
/// chat is 0x06 on protocol 767, 0x07 on 768-770 and 0x08 from 771, and clientbound system chat moves
/// four times across the same range. An unrecognized version means "stop inspecting, keep proxying at
/// the frame level" — never a best-guess fallback.''')

p.write_text(s, encoding='utf-8')

print(f'registry regenerated with {len(entries)} versions')
for k in sorted(tables, key=int):
    print(f"  {k}: {tables[k]['version']}")
