"""Regenerates MessageDefaultHistory.cs from what every release actually shipped.

    python tools/generate-message-history.py

The control panel can offer to bring a message up to date only if it can tell an edited message from
an untouched one, and the only honest way to do that is to know what was shipped. A hand-written list
would rot the first time somebody forgot to add to it, and the failure would be silent and
destructive: a message somebody wrote themselves, quietly replaced.

So the list is not written by hand. Every v1.* tag's appsettings.json is read, and every value each
message has ever had is recorded. Run this after changing a default message, and commit the result.
"""
import json
import re
import subprocess
from pathlib import Path

SOURCE = Path('src/MinecraftFirewall.Proxy/appsettings.json')
OUTPUT = Path('src/MinecraftFirewall.App/Services/MessageDefaultHistory.cs')

STRING = r'"(\w+)":\s*("(?:[^"\\]|\\.)*")'


def messages_of(text):
    """The Messages section's string values. Deliberately tolerant: an older file may hold keys this
    one does not, and vice versa."""
    start = text.index('"Messages"')
    found = {}

    for match in re.finditer(STRING, text[start:]):
        try:
            found[match.group(1)] = json.loads(match.group(2))
        except json.JSONDecodeError:
            pass

    return found


current = messages_of(SOURCE.read_text(encoding='utf-8'))

previous = {}
tags = subprocess.check_output(['git', 'tag', '--list', 'v1.*'], text=True).split()

for tag in tags:
    try:
        text = subprocess.check_output(
            ['git', 'show', f'{tag}:{SOURCE.as_posix()}'],
            text=True, encoding='utf-8', stderr=subprocess.DEVNULL)
    except subprocess.CalledProcessError:
        continue  # a tag from before the file existed

    for key, value in messages_of(text).items():
        previous.setdefault(key, set()).add(value)

# Every shipped value that is not the current one. A later tag carrying the current value does not
# make the earlier ones stop existing — somebody upgrading from an old release still has the old text
# in their file, and they are exactly who this is for.
history = {
    key: sorted(value for value in values if value != current.get(key))
    for key, values in previous.items()
    if key in current
}
history = {key: values for key, values in history.items() if values}


def literal(value):
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


entries = []
for key in sorted(history):
    values = ',\n            '.join(literal(v) for v in history[key])
    entries.append(f'        ["{key}"] =\n        [\n            {values},\n        ],')

OUTPUT.write_text('''namespace MinecraftFirewall.App.Services;

/// <summary>
/// Every value each player-facing message has shipped with in an earlier release.
///
/// This exists to answer one question safely: has somebody edited this message, or is it simply old?
/// Configuration wins over the compiled defaults — which is right, it is their file — but it means a
/// default that improves in a new release never reaches anybody who installed an older one. Their
/// prompts stay as they were, and there is nothing to tell them why.
///
/// A message whose current value is one this project shipped is a message nobody has touched, and
/// bringing it up to date takes nothing from them. A message that matches none of them was written by
/// a person, and is never touched.
///
/// Generated by tools/generate-message-history.py, which reads every v1.* tag rather than trusting
/// anybody to maintain a list. A list kept by hand would rot the first time somebody forgot to add to
/// it, and it would fail in the worst direction: silently replacing something somebody wrote.
/// </summary>
public static class MessageDefaultHistory
{
    /// <summary>Message key to the values it has had in earlier releases, newest release last.</summary>
    public static readonly IReadOnlyDictionary<string, string[]> PreviousDefaults =
    new Dictionary<string, string[]>(StringComparer.Ordinal)
    {
''' + '\n'.join(entries) + '''
    };

    /// <summary>True when this text is one an earlier release shipped, which means nobody has edited
    /// it and replacing it takes nothing away.</summary>
    public static bool IsAnUneditedDefault(string key, string value) =>
        PreviousDefaults.TryGetValue(key, out string[]? values) &&
        Array.IndexOf(values, value) >= 0;
}
''', encoding='utf-8')

print(f'{len(tags)} tags read; {len(history)} message(s) with earlier defaults written to {OUTPUT}')
